### ISSUE TITLE
Caliper generates reports of TPS issues encountered!!!  6Tps?

### ISSUE THREAD

**Issue by zsh122958** [hyperledger/caliper#333] opened 2019-02-28 10:04 UTC
Caliper generates reports of TPS issues encountered
Pressure test 1000 trades 100tps
The first problem arose when the transaction was sent
Below the figure is the generated TPS report
![image](https://user-images.githubusercontent.com/44695130/53557890-df055780-3b81-11e9-8934-3637eabfca58.png)

The sync-request function is introduced in sending transactions
The success of the transaction is shown in the figure below.
{ code: '0000',
  msg: 'exec successfully',
  txid: '74ee9d9890ae45d687ac58cad26d07fb' }

![image](https://user-images.githubusercontent.com/44695130/53558047-3277a580-3b82-11e9-9309-c58b8554772b.png)

Use the function request-promise introduced by asynchronous sending transactions
The blockchain network could not receive information if the transaction failed, as shown in the figure

![image](https://user-images.githubusercontent.com/44695130/53558157-62bf4400-3b82-11e9-82e1-e612a092d0cb.png)

Here is the TPS I tested manually

![image](https://user-images.githubusercontent.com/44695130/53558319-c0539080-3b82-11e9-9816-cbebd27e6f82.png)

How to better position the way of the problem!!!
I think it's because the synchronization function affects TPS

**Comment by aklenik** [comment] 2019-02-28 14:36
@zsh122958 I think we'll need more context. Especially about your user test module, since it can affect the precision of scheduling, and it's written by you :)

**Comment by zsh122958** [comment] 2019-03-01 02:31
@aklenik 
This is my test configuration file
![image](https://user-images.githubusercontent.com/44695130/53612312-cdb55d00-3c0c-11e9-9055-c899b11f63c9.png)

invokeSmartContract Send a deal
![image](https://user-images.githubusercontent.com/44695130/53612376-11a86200-3c0d-11e9-9596-bd78dc54cbb9.png)

**Comment by aklenik** [comment] 2019-03-01 10:47
@zsh122958 As I see, you wrote your own adapter to support a new platform. In that case, most of the code that is running is your own code. The critical path is the following for Caliper:

rate controller => user test module => invokeSmartContract => rate controller => ...

You use 5 client processes to generate a 200TPS workload, which means 40TPS per client process. This means that the rate controller code needs to be executed at least every 24ms to keep this pace. If you use more client, then this number can be higher (20 client => 10 TPS per client => 100ms duration between rate controller calls).

General advice: **don't use sync calls** in this path. I think line 54 is your problem. It blocks the event loop of Node.js so the rate controller is not called quickly enough. You should use async calls instead (the code will hardly change with the async/await pattern).

**Comment by zsh122958** [comment] 2019-03-04 03:53
Thank you very much!
I'm going to do it asynchronously.
This is the report graph received.
![image](https://user-images.githubusercontent.com/44695130/53709560-e70c1280-3e73-11e9-8554-058f95d0b53f.png)
This is something that bothers me a lot, or is there a better way? I'm trying to locate the TPS problem

**Comment by zsh122958** [comment] 2019-03-04 03:54
In the underlying database of blockchain, 5,000 pieces of data are received.

**Comment by shiningfrog** [comment] 2019-03-04 04:15
@zsh122958 hello, now your tps result seems very good, could you advice me how you build your network? what's your configuration? what block chain you test? fabirc?

**Comment by zsh122958** [comment] 2019-03-04 05:06
@shiningfrog  
How are you
We're testing our own blockchain
There are still some problems with the test results at present, if the test is successful later.
We can communicate with each other.

**Comment by shiningfrog** [comment] 2019-03-04 05:47
@zsh122958 ok, thank you! by the way, could you give some advice in how to improve the tps first? my tps is only 20+ in caliper(open.js).

**Comment by panyu4** [comment] 2019-03-04 06:09
@zsh122958 ， the result shows the backend blockchain system throughput equals to the successful transactions' number. It is caused by original bug, and was fixed by  PR #274 .  You can use the newest version test it again.

**Comment by zsh122958** [comment] 2019-03-04 07:33
@shiningfrog  
I used synchronous transaction before, resulting in low Tps.
Try launching multiple local clients.

**Comment by aklenik** [comment] 2019-03-04 20:30
@zsh122958 As @panyu4 suggested, try rebasing your code to the up-to-date Caliper version, it had some bugs fixed recently. It shouldn't affect your adapter code.

**Comment by zsh122958** [comment] 2019-03-05 03:17
@aklenik 
This is the latest version of my use of caliper.
Asynchronous commit is currently used.
The operation is as follows:
![image](https://user-images.githubusercontent.com/44695130/53778455-c3aa9b80-3f37-11e9-9541-c34c8227e22e.png)

info: [bench-flow.js]: 
r.create.max: 1551755287.142
 r.create.min: 1551755277.155 
 r.final.max: 1551755287.145 
 r.final.min: 1551755278.087

**Comment by aklenik** [comment] 2019-03-11 13:49
@zsh122958 Can you share the entire code file of your adapter (as GitHub gist)? The TPS is still shady in your report.

**Comment by aklenik** [comment] 2019-09-05 13:51
Relating to a custom adapter implementation, closing it.

**Closed by aklenik** 2019-09-05 13:51 UTC
Labels: consult
