### ISSUE TITLE
Chaincode Error - Abnormal account

### ISSUE THREAD

**Issue by sathishNS** [hyperledger/caliper#143] opened 2018-07-26 07:29 UTC
Hi,

I ran the simple benchmark with the default config.json and i end up with below errors. Attaching the same
![abnormal_account](https://user-images.githubusercontent.com/36123375/43247844-94871580-90d3-11e8-9154-dee7631d848b.JPG)
![timeout](https://user-images.githubusercontent.com/36123375/43247854-9be5de9c-90d3-11e8-88b2-f83927330f90.JPG)
![fail](https://user-images.githubusercontent.com/36123375/43247875-a6c170f6-90d3-11e8-8d17-b872858e74d4.JPG)

Thanks,
Sathish

**Comment by aklenik** [comment] 2018-07-26 17:44
@sathishNS The submitted transactions that should create those accounts probably timed out. So when you want to query it, it doesn't exist, and the chaincode handles this by throwing this error. So this is the expected behavior of the chaincode.

This chaincode line throws the error: https://github.com/hyperledger/caliper/blob/master/src/contract/fabric/simple/go/simpletest.go#L107

**Comment by sathishNS** [comment] 2018-08-01 11:45
@aklenik so basically how to increase the timeout for this ? is it hardcoded value?

Also in the final "All test results" there are number of failures. what does that mean?

**Comment by houqinghui** [comment] 2018-11-06 08:33
@sathishNS   have you solved the problem?   you can take a look at Issue #175 
if you wang increase the timeout , you can refer to Issue #137

**Comment by aklenik** [comment] 2018-11-06 13:29
@sathishNS You can increase the transaction timeout on the client/Caliper side in your callback module when calling the `invokeSmartContract()` function (the last parameter is the timeout in seconds, but take a look at the sample callbacks, like the ones in the `simple` benchmark directory).

You can increase the transaction timeout on the peer side by passing the following environment setting somehow (in the docker compose file for example): `CORE_CHAINCODE_EXECUTETIMEOUT=120s`

**Comment by aklenik** [comment] 2018-11-14 21:57
Since this is a timeout configuration issue and the benchmark exhibits the expected behavior, I'm closing the issue.

**Closed by aklenik** 2018-11-14 21:57 UTC
