### ISSUE TITLE
Cannot specify config file in 'npm test' command while running caliper

### ISSUE THREAD

**Issue by knurherb** [hyperledger/caliper#174] opened 2018-09-06 08:35 UTC
According to the [documentation](https://github.com/hyperledger/caliper), caliper can be run alternatively by issuing an `npm test` command while also specifying a config file as well as fabric-config file through the command like so:

```
npm test -- simple -c ./benchmark/simple/config.json -n ./benchmark/simple/fabric.json
```

The test was able to run successfully and generated the .html report within the `benchmark` folder of the `simple` fabric caliper test. However, the test ran with its default config and fabric config file. Thus, I executed the default `simple` test instead of the tests defined in my own config files. I attempted to use the same fabric config file so the command I executed was : 

```
node benchmark/simple/main.js  -c ./benchmark/simple/my-own-config.json
```
As an additional note, Executing the test without `npm` yield expected results, but the .html file was generated within the root of the caliper folder.

**Comment by houqinghui** [comment] 2018-11-06 07:57
@knurherb   i cannot get your point. your meaning is that the location of the .html file is wrong?

**Comment by aklenik** [comment] 2018-11-06 10:59
@knurherb I think the HTML file is generated in the current working directory, which is the root Caliper folder in the second case. As for the `npm test` problem, I'll try to reproduce the issue.

**Comment by houqinghui** [comment] 2018-11-13 11:34
@knurherb 

1. now the command `npm test ` and `node` will generate the .html file whose location is same within the /caliper/benchmark/simple. 
2. the command `npm test` is the encapsulation of `node`,  you can test your own config files, but please write the complete command.

**Comment by houqinghui** [comment] 2018-11-13 11:36
@panyu4   i think the issue can be closed.

**Comment by panyu4** [comment] 2018-11-27 14:04
since no more activities and it looks be resolved, I'm closing this issue.

**Closed by panyu4** 2018-11-27 14:04 UTC
