### ISSUE TITLE
Make logging consistent

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#536] opened 2019-07-31 10:14 UTC
The current logging situation is a little bit ad-hoc. There is no enforced standard, and we would benefit greatly from a serviceability and usability point if we were to enforce logging standards across the Caliper code base.

We should be logging at debug level:
- [ ] entry/exit from every method, including passed values

We should be logging at error level
- [ ] every error thrown through the code

We should be logging at info level:
- [ ] caliper lifecycle items
- [ ] round information and basic statistics (we do this already)

**Comment by amogh-jrules** [comment] 2019-11-28 16:25
Hey I would like to contribute to Caliper, starting with this issue.

**Comment by aklenik** [comment] 2019-11-29 10:18
@amogh-jrules Awesome! To get familiar with the logging aspects you can refer to this doc page: https://hyperledger.github.io/caliper/vNext/logging/
We're changing a LOT of the core code right now, so give us a few days to finish it, just to avoid a conflict hell :) 
And drop by the next Caliper call, so we can have a discussion about the logging rules/guidelines:
https://github.com/hyperledger/caliper/wiki/Caliper-Calls

**Comment by amogh-jrules** [comment] 2019-11-29 11:26
Thanks, I'll do that!

**Comment by amogh-jrules** [comment] 2019-12-20 18:26
Hey, may I begin?

**Comment by aklenik** [comment] 2020-01-08 13:20
@amogh-jrules Sorry for the late reply. After PR #682 is merged, you can start working on the "master modules" in the following directory: https://github.com/hyperledger/caliper/tree/master/packages/caliper-core/lib/master

Until that time you can still inspect the different SUT adapters whether they require additional logging (probably yes). I'd recommend to start with the following adapters: Fabric, Ethereum, Sawtooth and FISCO-BCOS. 
One thing to look out for: the `invokeSmartContract` and `querySmartContract` methods are considered hot paths, so they're performance critical, try not to stringify big objects during logging.

**Comment by amogh-jrules** [comment] 2020-01-08 19:51
Okay, thanks, if I have some queries where can I discuss them? Is there a community channel for this project?

**Comment by aklenik** [comment] 2020-01-09 11:19
@amogh-jrules Yes, see the Communication section of this page:
https://wiki.hyperledger.org/display/caliper

**Comment by Tezas-6174** [comment] 2022-05-01 07:13
Is this issue resolved? If not can you explain a bit about the issue? 

I am new to this ecosystem but would like to start with this issue if it's open. Please share some beginner-friendly resources if possible.

**Comment by aklenik** [comment] 2022-05-02 09:12
The issue is far from resolved, so every contribution is welcome! Check the following doc for guidelines on contributing: https://github.com/hyperledger/caliper/blob/main/CONTRIBUTING.md

**Comment by Tezas-6174** [comment] 2022-05-05 01:23
Ok. Thank you!

Checked ``CONTRIBUTING.md``,

**Comment by aklenik** [comment] 2022-05-11 14:58
@Tezas-6174 That sounds like a good workflow. Correcting error message per package sounds reasonable

**Comment by Tezas-6174** [comment] 2022-05-12 01:37
Yes. So now, I will start by working on ``caliper-cli`` package following the above workflow. 

Thank you.

**Closed** 2022-06-27 10:23 UTC
Labels: enhancement, good first issue

**Comment by anshikavashistha** [comment] 2024-05-04 10:51
May I work on this issue ?
@aklenik @nklincoln
