### ISSUE TITLE
Change declared API from _sendSingleRequest and sendRequestBatch to just be sendRequest

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#998] opened 2020-09-16 09:06 UTC
Currently there are 2 public apis
_sendSingleRequest is a public api (but in Java/Typescript terms is a protected api) for connector developers
sendRequestBatch is a public api for workload developers

This issue is to get rid of the public batch method and have a single public api for both connector developers and workload developers called `sendRequest`

**Comment by aklenik** [comment] 2020-09-16 10:21
I think the problem is that we are trying to do two things in the class:
* Declare an interface for connectors
* Provide _partial_ default implementations for some methods, requiring some delegate methods (`_sendSingleRequest`).

With the loose signatures in JS, this creates some confusion.
My suggestion would be the following:
1. Declare a `BlockchainConnector[Interface]` class purely with the methods of the public API (throwing `NotImplementedException`s). This interface will be in every signature/doc-tag when a connector is passed around.
2. Implement a `BlockchainConnectorBase` class  that provides partial default implementations where possible (almost for every method). This can be used by connector developers to simplify their implementation (or implement the interface directly).

**Closed** 2020-09-23 16:09 UTC
