### ISSUE TITLE
Couldn't read configuration binary for mychannel: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Luciferjason** [hyperledger/caliper#818] opened 2020-04-25 13:27 UTC
I am installing hyperledger caliber using the local NPM found at https://hyperledger.github.io/caliper/v0.3/installing-caliper/. Once I invoke the local CLI binary (step 4) using the command,
npx caliper launch master
--caliper-workspace .
--caliper-benchconfig benchmarks/scenario/simple/config.yaml
--caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml

I got the following log error:
root@jason-virtual-machine:~/go/src/github.com/hyperledger/caliper-benchmarks# sudo  npx caliper launch master \
>     --caliper-workspace . \
>     --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
>     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
2020.04.25-21:14:27.041 info  [caliper] [cli-launch-master] 	Set workspace path: /root/go/src/github.com/hyperledger/caliper-benchmarks
2020.04.25-21:14:27.042 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /root/go/src/github.com/hyperledger/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.04.25-21:14:27.042 info  [caliper] [cli-launch-master] 	Set network configuration path: /root/go/src/github.com/hyperledger/caliper-benchmarks/networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
2020.04.25-21:14:27.043 info  [caliper] [cli-launch-master] 	Set SUT type: fabric
2020.04.25-21:14:27.046 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.04.25-21:14:27.047 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.04.25-21:14:27.058 info  [caliper] [adapters/fabric] 	Initializing standard adaptor compatible with installed SDK: 1.4.0
2020.04.25-21:14:27.562 info  [caliper] [caliper-utils] 	Executing command: cd .; export FABRIC_VERSION=1.4.1;export FABRIC_CA_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating ca.org2.example.com ... done
Creating ca.org1.example.com ... done
Creating orderer.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
2020.04.25-21:14:36.998 info  [caliper] [caliper-engine] 	Executed start command in 9.437 seconds
2020.04.25-21:14:36.999 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.0; TLS: none
2020.04.25-21:14:37.613 info  [caliper] [adapters/fabric] 	Org1's registrar enrolled successfully
2020.04.25-21:14:37.804 info  [caliper] [adapters/fabric] 	Org2's registrar enrolled successfully
2020.04.25-21:14:37.820 info  [caliper] [adapters/fabric] 	Org1's admin's materials are successfully loaded
2020.04.25-21:14:37.829 info  [caliper] [adapters/fabric] 	Org2's admin's materials are successfully loaded
2020.04.25-21:14:37.837 info  [caliper] [adapters/fabric] 	client0.org1.example.com's materials are successfully loaded
2020.04.25-21:14:37.847 info  [caliper] [adapters/fabric] 	client0.org2.example.com's materials are successfully loaded
2020.04.25-21:14:37.848 info  [caliper] [adapters/fabric] 	Channel 'mychannel' definiton being retrieved from file
2020.04.25-21:14:37.849 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: Couldn't read configuration binary for mychannel: EISDIR: illegal operation on a directory, read
2020.04.25-21:14:37.849 info  [caliper] [caliper-engine] 	Executed "init" step in 0.851 seconds
2020.04.25-21:14:37.850 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Stopping peer0.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping ca.org1.example.com    ... done
Stopping ca.org2.example.com    ... done
Removing peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.04.25-21:14:49.582 info  [caliper] [caliper-engine] 	Executed end command in 11.732 seconds
2020.04.25-21:14:49.583 error [caliper] [cli-launch-master] 	Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

选项：
  --help, -h           Show usage information  [布尔]
  --version            Show version information  [布尔]
  --caliper-bind-sut   The name and version of the platform to bind to  [字符串]
  --caliper-bind-cwd   The working directory for performing the SDK install  [字符串]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [字符串]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [字符串]

Error: Benchmark failed with error code 4
    at Function.handler (/root/go/src/github.com/hyperledger/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

and When I do 
./generate.sh 
I also got some errors as follow :
 ./generate.sh 

Pull Hyperledger Fabric binaries

===> Downloading version 2.1.0 platform specific fabric binaries
===> Downloading:  https://github.com/hyperledger/fabric/releases/download/v2.1.0/hyperledger-fabric-linux-amd64-2.1.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 3 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 3 seconds. 4 retries left.
100   654  100   654    0     0    437      0  0:00:01  0:00:01 --:--:--   437
100 72.7M  100 72.7M    0     0   265k      0  0:04:40  0:04:40 --:--:--  284k
==> Done.
===> Downloading version 1.4.6 platform specific fabric-ca-client binary
===> Downloading:  https://github.com/hyperledger/fabric-ca/releases/download/v1.4.6/hyperledger-fabric-ca-linux-amd64-1.4.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   657  100   657    0     0    248      0  0:00:02  0:00:02 --:--:--   248
100 23.3M  100 23.3M    0     0   252k      0  0:01:34  0:01:34 --:--:--  276k
==> Done.
org1.example.com
org2.example.com
org3.example.com
2020-04-25 21:03:40.804 CST [common.tools.configtxgen] main -> INFO 001 Loading configuration
2020-04-25 21:03:40.809 CST [common.tools.configtxgen.localconfig] completeInitialization -> INFO 002 orderer type: solo
2020-04-25 21:03:40.809 CST [common.tools.configtxgen.localconfig] Load -> INFO 003 Loaded configuration: /root/go/src/github.com/hyperledger/caliper-benchmarks/networks/fabric/config_solo/configtx.yaml
2020-04-25 21:03:40.809 CST [common.tools.configtxgen] main -> FATA 004 Error on outputBlock: could not create bootstrapper: could not create channel group: error adding policies to channel group: no policies defined
2020-04-25 21:03:40.845 CST [common.tools.configtxgen] main -> INFO 001 Loading configuration
2020-04-25 21:03:40.850 CST [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /root/go/src/github.com/hyperledger/caliper-benchmarks/networks/fabric/config_solo/configtx.yaml
2020-04-25 21:03:40.850 CST [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
2020-04-25 21:03:40.850 CST [common.tools.configtxgen] main -> FATA 004 Error on outputChannelCreateTx: could not generate default config template: error parsing configuration: error adding policies to channel group: no policies defined

Due to the problem of Chinese network, I had to make the following modifications to the generate.sh . The  bootstrap.sh is copyied from curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.1.0 1.4.6 0.4.18 -ds
#!/usr/bin/env bash

# if the binaries are not available, download them
if [[ ! -d "bin" ]]; then
  sed -i 's/\r$//' bootstrap.sh
  chmod u+x bootstrap.sh
  ./bootstrap.sh  -ds
fi

rm -rf ./crypto-config/
rm -f ./orgs.genesis.block
rm -f ./mychannel.tx

# The below assumes you have the relevant code available to generate the cryto-material
./bin/cryptogen generate --config=./crypto-config.yaml
./bin/configtxgen -profile OrgsOrdererGenesis -outputBlock orgs.genesis.block -channelID syschannel
./bin/configtxgen -profile OrgsChannel -outputCreateChannelTx mychannel.tx -channelID mychannel

# Rename the key files we use to be key.pem instead of a uuid
for KEY in $(find crypto-config -type f -name "*_sk"); do
    KEY_DIR=$(dirname ${KEY})
    mv ${KEY} ${KEY_DIR}/key.pem
done

**Comment by nklincoln** [comment] 2020-04-29 13:15
I'm confused to what the issue is, from what I can gather from the above:
- you were missing the Fabric crypto-config files, which are intentionally omitted from the repository
- when you generated them for use, it was ok

?

**Comment by aklenik** [comment] 2020-04-29 13:45
@Luciferjason It seems like you're downloading Fabric 2.1 binaries and use them with a 1.4 configtx file. That won't work.

**Comment by Luciferjason** [comment] 2020-04-30 09:22
Thank you very much. I re-downloaded the Fabric 1.4 binary files. It's ready to run.

**Comment by aklenik** [comment] 2020-04-30 10:25
@Luciferjason I take that means the issue is solved, so I'm closing it.

**Closed by aklenik** 2020-04-30 10:25 UTC
Labels: question
