### ISSUE TITLE
Reduce amount of info logging

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#739] opened 2020-02-20 18:01 UTC
Currently there is quite a large amount of information based logging. A large proportion of this is more appropriately classified as debug level logging.

This issue is to address the logging that is being output and classify the logging appropriately: 
- Info level: Caliper phases/progress
- Debug level: non progress related information in caliper; all adaptor logging
- Error: All error instances

**Comment by aklenik** [comment] 2020-11-04 10:16
Closing this, since the issue is covered by #536

**Closed by aklenik** 2020-11-04 10:16 UTC
Labels: enhancement
