### ISSUE TITLE
Hyperledger caliper TrustedBench  提交invokeSmartContract（）时，发送http.request请求   没有响应 到达一定时间 程序停止

### ISSUE THREAD

**Issue by zsh122958** [hyperledger/caliper#266] opened 2018-12-19 11:48 UTC
/**
     * Invoke the given chaincode according to the specified options. Multiple transactions will be generated according to the length of args.
     * @param {object} context The Fabric context returned by {getContext}.
     * @param {string} contractID The name of the chaincode.
     * @param {string} contractVer The version of the chaincode.
     * @param {Array} args Array of JSON formatted arguments for transaction(s). Each element containts arguments (including the function name) passing to the chaincode. JSON attribute named transaction_type is used by default to specify the function name. If the attribute does not exist, the first attribute will be used as the function name.
     * @param {number} timeout The timeout to set for the execution in seconds.
     * @return {Promise<object>} The promise for the result of the execution.
     */
    invokeSmartContract(context, contractID, contractVer, args, timeout) {
        commUtils.log('  >>> Into invokeSmartContract >>>>');
        args.forEach(function(item,index) {
            let con = require('../../benchmark/uchains_simple/uchains.json');
            let restApiUrl = con.uchains.network.restapi.url;
            let configPort = con.uchains.network.restapi.port;
            const http = require('http');
            let options = {
                hostname:restApiUrl,     //此处不能写协议，如 ： http://,https://  否则会报错
                port:configPort,
                path:'/UChains/poe/poe/transaction',
                method:'POST',
                headers: {
                    'Content-Type':'application/x-www-form-urlencoded',
                    'Content-Length':Buffer.byteLength(item.acount)
                }
            };
            commUtils.log('________Send__________',restApiUrl,configPort);
            let req ;
            try{
                req = http.request(options,function(res){
                    commUtils.log('________success_________');
                    commUtils.log('STATUS:'+res.statusCode);
                    commUtils.log('HEADERS:'+JSON.stringify(res.headers));
                    res.on('data',function(chunk){
                        commUtils.log('BODY:'+chunk);
                    });
                });
            }
            catch(err) {
                commUtils.log(err);
            }
            req.write(item.acount);
            req.end();
            commUtils.log('  >>>index>>>>');
        });
        return Promise.resolve();
    }

**Comment by houqinghui** [comment] 2018-12-20 02:10
@zsh122958 what do you mean?  if some errors appear, please list the error log information.

**Comment by aklenik** [comment] 2018-12-20 11:07
@zsh122958 Could you give more details, please? For me, it looks like a custom version of Caliper. Also, could you keep the language of the issue English, so it reaches more people? :sweat_smile:

**Comment by zsh122958** [comment] 2018-12-20 16:58
@houqinghui  
The underlying service that sent the post request did not receive it
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
案例来源于 https://github.com/hyperledger/caliper/blob/master/benchmark/simple/open.js
行
返回bc.invokeSmartContract（contx，'simple'，'v0'，{verb：' open'，account：newAcc，money：initMoney}，30）;

**Comment by zsh122958** [comment] 2018-12-25 01:38
@panyu4 @houqinghui @aklenik 
Thank you. I re-referenced a sync-request package and sent the request request. The transaction was successfully sent.Now we're doing a query

**Comment by panyu4** [comment] 2018-12-25 01:45
@zsh122958 ， Good News. Would you please list some more details? It might be one choice to resolve this problem.

**Comment by zsh122958** [comment] 2018-12-25 01:54
@panyu4  
sync-request
https://www.npmjs.com/package/sync-request
https://www.jianshu.com/p/8112efecb0ad      Test

**Comment by zsh122958** [comment] 2018-12-25 06:54
@panyu4 I would like to know the setting of the timeout and whether the number of submissions can be set.

**Comment by panyu4** [comment] 2018-12-25 07:46
@zsh122958 ， the timeout you can set in your test file( the callback property you defined in configuration file).  Just as an example, in the file `benchmark/simple/open.js`  the run function calls the blockchain NBI invokeSmartContract and the last parameter is the timeout setting.  In the file `Config/default.yaml`, the property [client-request-timeout](https://github.com/hyperledger/caliper/blob/e7409cc847cd87f36f4456905fc7e5e3b4584c20/config/default.yaml#L2) can be set by yourself. 
The number of submissions ==> Do you mean the total transactions' number? If so, you can defined like [this](https://github.com/hyperledger/caliper/blob/e7409cc847cd87f36f4456905fc7e5e3b4584c20/benchmark/simple/config.yaml#L11)

**Comment by zsh122958** [comment] 2018-12-25 08:08
@panyu4  sorry，I development project is https://github.com/TrustedBlockchain/TrustedBench，The configuration file is not available，The problem I am facing now is that the txnumber I set according to the config.json configuration file is 1000, and the result of submitting the transaction does not stop, but is executed all the time.You don't go to the query method queryState。

**Comment by panyu4** [comment] 2018-12-25 08:14
@zsh122958 ， the cause of your problem is just what I said above. In that fork, I submitted a pr and it has not been merged. You can use it and set the rate control to be fixed-feedback-rate.

**Comment by zsh122958** [comment] 2018-12-25 08:53
I'm breaking down. Smile @panyu4

**Comment by panyu4** [comment] 2018-12-25 08:59
@zsh122958 ， now we are trying to fix this problem. You may try later.
You'd better reduce the tx number, and there will be a boundary value. Set the number less than this value ,  it can run well.

**Comment by zsh122958** [comment] 2018-12-25 09:03
Thanks,Txnumber100 TPS 10,query 100 TPS 10. Still sending transactions continuously, may I ask you privately? @panyu4

**Comment by zsh122958** [comment] 2018-12-26 00:33
Ok, please send me your WeChat ID to learn from you.@panyu4

**Comment by panyu4** [comment] 2018-12-26 00:41
@zsh122958 , I think put the resolve process here would be better. Other people will know how to handle the same problem.

**Comment by zsh122958** [comment] 2018-12-26 00:49
This is good, help more people solve the problem. I upload the error to #271, trouble




| |
校长
|
|
邮箱：18234444581@163.com
|

签名由 网易邮箱大师 定制

在2018年12月26日 08:41，panyu4 写道：

@zsh122958 , I think put the resolve process here would be better. Other people will know how to handle the same problem.

**Comment by panyu4** [comment] 2019-02-12 01:04
Current Caliper is able to support file mode which means it can run with large scale test, so the time out errors will be reduced.   Actually, this issue was caused by the incorrect writing of adapters. Please refer to  [the related adapter's documentation](https://hyperledger.github.io/caliper/docs/Writing_Adapters.html) and this issue will be closed.

**Closed by panyu4** 2019-02-12 01:04 UTC
