### ISSUE TITLE
FabricCAClientService.js

### ISSUE THREAD

**Issue by Elhamshammar** [hyperledger/caliper#1155] opened 2021-08-29 19:48 UTC
I am a new to caliper 
I would like to benchmark my network
Fabric sdk 2.1
Caliper 0.4.0

Once I launch  master command it showed me the following error

error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: Client network socket disconnected before secure TLS connection was established], stack=Error: Calling enrollment endpoint failed with error [Error: Client network socket disconnected before secure TLS connection was established]

**Comment by davidkel** [comment] 2022-01-17 10:16
duplicate of #1154

**Closed by davidkel** 2022-01-17 10:16 UTC
