### ISSUE TITLE
principle of TPS calculation

### ISSUE THREAD

**Issue by lenoAlex** [hyperledger/caliper#247] opened 2018-12-04 09:42 UTC
Recently I did some performance testing on fabric with caliper. However, I am confused about the principle of TPS calculation of caliper. Could you please give a brief specification about it? How it works?

**Comment by houqinghui** [comment] 2018-12-05 15:12
@lenoAlex   hello, the throughout TPS  = Success Tx / time. you can look the function processResult and getResultValue at the  [https://github.com/hyperledger/caliper/blob/master/src/comm/bench-flow.js](url)

**Comment by houqinghui** [comment] 2018-12-21 02:09
Caliper will record the submitting time and committing time (the time when the tx is committed on the ledger or when the failure occurred) for each tx.
So the send rate is calculated by (Succ+Fail) / (last submitting time - first submitting time).
The throughput is calculated by Succ/(last committing time - first submitting time), here only successful committed txs will be calculated.
@lenoAlex

**Comment by aklenik** [comment] 2018-12-22 17:46
Since the issue is a question, and it's answered, I'm closing it.

**Closed by aklenik** 2018-12-22 17:46 UTC
