### ISSUE TITLE
How to test TPS in orderer with kafka

### ISSUE THREAD

**Issue by BeanChan1987** [hyperledger/caliper#107] opened 2018-06-28 09:10 UTC
Scene one:
    1、Environment：orderer(solo)  org1(peer1,peer2)  org2(peer1,peer2)  ca0 ca1
    2、Start all nodes
    3、Config  caliper & Run test，the TPS is 440
Scene two:
     1、Environment: 2orderer(kafka modle)  4 kafka  3 zookeeper  org1(peer1,peer2) org2(peer1,peer2) ca0  ca1
    2、Start all nodes
    3、Config  caliper & Run test，the TPS is 20

why?
why TPS is so low?

**Comment by haojun** [comment] 2018-06-29 01:49
Emm, I can't see why there is such big performance difference.
Are you starting all nodes on the same machine in kafka mode? If yes, have you checked the system resources(cpu, memory) to see if the resources are exhausted? Also you can reduce the sending rate for example to 300 to see if fabric can handle and you can also test for a longer time to avoid possible cold start.

**Comment by BeanChan1987** [comment] 2018-07-02 03:53
1、4 machine
2、sending rate set to 40
3、cpu loading < 50% memory < 40%
4、caliper send TS failed and TPS is very low.

**Comment by BeanChan1987** [comment] 2018-07-02 03:57
I hava change the sending rate to 300，200，150，100，80，50，40 and so on, unable to  promoted the TPS.

**Comment by cao0507** [comment] 2018-10-23 12:34
@BeanChan1987 您好，请问您是怎么用 caliper 来测试多个 Orderer 节点的 fabric 网络的呢？网络配置文件 fabric.json 文件中的 orderer 部分该如何配置啊？

**Comment by shiningfrog** [comment] 2019-02-12 06:40
hello, is there some details in how to fill the fabric.json file to test the performance under kafka mode?

**Comment by aklenik** [comment] 2019-02-15 12:36
@shiningfrog The current Fabric adapter only supports a single orderer node. Check out PR #296 that supports multiple orderer endpoints. Not merged yet, and any feedback is welcome!

**Comment by shiningfrog** [comment] 2019-02-19 07:23
hello, i've clone this tree and tesed in multi orderers. when i try to test tps in my own fabirc network(1.2 kafka) , i got this error in Instantiating Step(installing ok) :'commit timeout for simple@v0' in XXX_channel for peer1.org2.example.com. i want to know if this is caused by the smart contract? @aklenik

**Comment by aklenik** [comment] 2019-02-19 09:22
@shiningfrog Check the peer logs or the chaincode container log for details.

**Comment by shiningfrog** [comment] 2019-02-19 11:19
thank you！ now i can 'succcessfully instantiated simple@v0 in XXXX_channel', and the test start. but there is another problem:'(node:XXX) unhandledPromiseRejectionWarning: Unhandled promise rejection(rejection id:3): TpyeError: Cannot read property 'simple@v0' of undefined'. could you provide some advices?
![image](https://user-images.githubusercontent.com/10084283/53011395-379a6d80-347b-11e9-854c-a6434cd60993.png)

**Comment by shiningfrog** [comment] 2019-02-20 06:44
thank you. now the  contract 'simple@v0' has instantiated in mychannel(i create a fabric network with 2 orderers and 4 peers, 2 orgs). but there is another problrm: [ChannelEventHub.js]: _connect - timed out after:45000 and unable to connect to the peer event hub.
i use fabric-1.2 to build up the whole network. is there any advice for me? @aklenik 
![image](https://user-images.githubusercontent.com/10084283/53071708-fa3aec00-351d-11e9-8b25-9318861c334a.png)
![image](https://user-images.githubusercontent.com/10084283/53071718-045cea80-351e-11e9-832d-5475c594ed8f.png)

**Comment by aklenik** [comment] 2019-02-20 11:31
@shiningfrog Hmm, it looks like that the transactions are not even processed. But it seems that the peers are available as an endpoint. Can you check the peer logs whether they're started successfully? The eventhub connect timeout suggest some peer errors

**Comment by aklenik** [comment] 2019-03-04 20:47
@shiningfrog Did you resolve this error?

**Comment by shiningfrog** [comment] 2019-03-05 03:32
@aklenik thank you very much!.sometimes it works well, but sometimes it doesn't. if i create a new chain network, this problrm fixed itself.   however when i test in the same chain, the problem raises again. i cannot see any error in peer logs and orderer logs.

**Comment by aklenik** [comment] 2019-03-05 09:08
@shiningfrog If you test it on an already running network, make sure you don't try to create channels again, and there is no conflict between the tests if you run them again without clearing their effects.

Since the testing of multiple orderers works, I'm closing this issue. If you run into any problem, open a new issue, with the detailed error logs from the network side.

**Closed by aklenik** 2019-03-05 09:08 UTC
Labels: question
