### ISSUE TITLE
Error while executing the benchmark: Error: Cannot find module 'fabric-ca-client/lib/FabricCAClientImpl.js'

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/caliper#231] opened 2018-11-27 08:59 UTC
When I use the command line 
`node benchmark/simple/main.js`
something goes wrong，

`Error while executing the benchmark: Error: Cannot find module 'fabric-ca-client/lib/FabricCAClientImpl.js'`
I have already installed fabric-ca-client

**Comment by MuckT** [comment] 2018-12-12 20:56
@aklenik I am receiving the same error using the same steps with fabric-ca-client@1.3.0.

**Comment by aklenik** [comment] 2018-12-22 17:47
@MuckT @zcyzhu The current adapter only supports Fabric up to the 1.2 version (inclusive). The required CA implementation file is probably moved into another directory in 1.3.0.

**Comment by YanLIU0822** [comment] 2019-01-17 06:45
I  meet the same issue. I solve this issue by uninstalling fabric-ca-client@1.14.0 and installing fabric-ca-client@1.2.0
hope it works for you guys

**Comment by panyu4** [comment] 2019-02-12 08:32
@zcyzhu , this is caused by the not match fabric SDK and Caliper. Now this problem is resolved by recently pr #279 . So close it.

**Closed by panyu4** 2019-02-12 08:32 UTC
